### ISSUE TITLE
Explain why this gem

### ISSUE THREAD

**Issue by nicolas-brousse** [komposable/dekorator#15]
Explain why we did this gem on README.

The main reason is: having something light compare to `draper` and after the presentation of @benoittgt about "Ruby memory, ActiveRecord and Draper" (https://medium.com/appaloosa-store-engineering/ruby-memory-activerecord-and-draper-64f06abeeb34).

**Comment by Spone** [comment]
What about this?

> **Dekorator** is a lightweight library to implement Presenters / Decorators in you Rails app. It has less features than `draper` and has a lower memory footprint.
>
> This gem has been inspired by our Rails development practices at Pantographe, and the [Ruby memory, ActiveRecord and Draper](https://medium.com/appaloosa-store-engineering/ruby-memory-activerecord-and-draper-64f06abeeb34) talk by @benoittgt.

**Comment by nicolas-brousse** [comment]
Too quick 😄 

Sounds good to me. Thanks!
